name: Deploy From Master

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Firebase
      run: |
        npm install -g firebase-tools
    - name: Install Dependencies & test
      run: |
        npm ci
    - name: Run Tests
      run: |
        npm test
    - name: Build
      run: |
        npm run build
    - name: Deploy
      run: |
        npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
