name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Firebase
      run: |
        npm install -g firebase-tools
    - name: Install Dependencies & test
      run: |
        npm ci
    - name: Run Tests
      run: |
        npm test
    - name: Build
      run: |
        npm run build
    - name: Deploy
      run: |
        echo "Deploying"
        npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
