name: Pull Requests Checks

on: 
  pull_request:
    branches:
    - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm ci
    - name: Linting Check
      run: |
        npm run lint && npm run lint:markdown
    - name: Run Tests
      run: |
        npm test
    - name: Test Build
      run: |
        npm run build
